# Generated by Django 5.1.2 on 2024-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('packing', 'Packing'), ('waiting_for_service', 'Waiting for Service'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='preparing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
